; Admin password for managing databases and access
admin_passwd = ${Sheletabatiste07}

; Database connection settings - use environment variables in your deploy
db_host = ${dpg-d2cj83mr433s73aoql9g-a}
db_port = ${5432}
db_user = ${sdtzvalues_user}
db_password = ${FSKw4Zkvs9FaPucl5uHMxHeIR7FBNNRN}

; The port Odoo will listen on
xmlrpc_port = 8069

; Logging (optional)
logfile = /var/log/odoo/odoo.log
log_level = info

; Enable multi-db support (recommended for SaaS setups)
dbfilter = ^%d$

; Disable demo data in production
demo = False
